# golangci-lint configuration for v2
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - nakedret
    - gocritic
    - revive
    - gosec

formatters:
  enable:
    - goimports

issues:
  exclude-generated: strict
