//go:build !ignore_autogenerated

/*
Copyright 2025 KubeAI Autoscaler Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicy) DeepCopyInto(out *AIInferenceAutoscalerPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicy) DeepCopy() *AIInferenceAutoscalerPolicy {
	if in == nil {
		return nil
	}
	out := new(AIInferenceAutoscalerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicyList) DeepCopyInto(out *AIInferenceAutoscalerPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIInferenceAutoscalerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicyList) DeepCopy() *AIInferenceAutoscalerPolicyList {
	if in == nil {
		return nil
	}
	out := new(AIInferenceAutoscalerPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicySpec) DeepCopyInto(out *AIInferenceAutoscalerPolicySpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	in.Metrics.DeepCopyInto(&out.Metrics)
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScaleBehavior)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(ScaleBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicySpec) DeepCopy() *AIInferenceAutoscalerPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AIInferenceAutoscalerPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicyStatus) DeepCopyInto(out *AIInferenceAutoscalerPolicyStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.CurrentMetrics != nil {
		in, out := &in.CurrentMetrics, &out.CurrentMetrics
		*out = new(CurrentMetrics)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *AIInferenceAutoscalerPolicyStatus) DeepCopy() *AIInferenceAutoscalerPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AIInferenceAutoscalerPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *CurrentMetrics) DeepCopyInto(out *CurrentMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *CurrentMetrics) DeepCopy() *CurrentMetrics {
	if in == nil {
		return nil
	}
	out := new(CurrentMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *GPUUtilizationMetric) DeepCopyInto(out *GPUUtilizationMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *GPUUtilizationMetric) DeepCopy() *GPUUtilizationMetric {
	if in == nil {
		return nil
	}
	out := new(GPUUtilizationMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *LatencyMetric) DeepCopyInto(out *LatencyMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *LatencyMetric) DeepCopy() *LatencyMetric {
	if in == nil {
		return nil
	}
	out := new(LatencyMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *MetricsSpec) DeepCopyInto(out *MetricsSpec) {
	*out = *in
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		*out = new(LatencyMetric)
		**out = **in
	}
	if in.GPUUtilization != nil {
		in, out := &in.GPUUtilization, &out.GPUUtilization
		*out = new(GPUUtilizationMetric)
		**out = **in
	}
	if in.RequestQueueDepth != nil {
		in, out := &in.RequestQueueDepth, &out.RequestQueueDepth
		*out = new(QueueDepthMetric)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *MetricsSpec) DeepCopy() *MetricsSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *QueueDepthMetric) DeepCopyInto(out *QueueDepthMetric) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *QueueDepthMetric) DeepCopy() *QueueDepthMetric {
	if in == nil {
		return nil
	}
	out := new(QueueDepthMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ScaleBehavior) DeepCopyInto(out *ScaleBehavior) {
	*out = *in
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ScalingPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function
func (in *ScaleBehavior) DeepCopy() *ScaleBehavior {
	if in == nil {
		return nil
	}
	out := new(ScaleBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *ScalingPolicy) DeepCopyInto(out *ScalingPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *ScalingPolicy) DeepCopy() *ScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}
